"""added summary to recipes model

Revision ID: 6b0b6eb522d0
Revises: edc6e2842d36
Create Date: 2020-09-01 00:02:51.251070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0b6eb522d0'
down_revision = 'edc6e2842d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'summary')
    # ### end Alembic commands ###
